### ISSUE TITLE
[BUG] Unable to link groups

### ISSUE THREAD

**Issue by FlechazoPh** [ehForwarderBot/efb-telegram-master#122]
When I click on the link group, it shows that I add a bot to the group, not the bind operation, resulting in the inability to link the WeChat group to the tg group

Logs:
```

[root@oracle-centos-2 ~]# journalctl -f -u efb.service -l
-- Logs begin at Tue 2022-05-10 19:21:32 CST. --
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: Traceback (most recent call last):
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/master_message.py", line 393, in process_telegram_message
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: slave_msg = coordinator.send_message(m)
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/coordinator.py", line 113, in send_message
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: return slaves[msg.deliver_to.channel_id].send_message(msg)
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 404, in send_message
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: r.append(self._bot_send_msg(chat, msg.text))
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 732, in _bot_send_msg
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: .format(code=e.err_code, message=e.err_msg))
May 11 09:35:57 oracle-centos-2 ehforwarderbot[23622]: ehforwarderbot.exceptions.EFBMessageError: Error from Web WeChat while sending message: [-1] This is an unknown error from Web WeChat which we know nothing about why this is happening. If you have seen a pattern or if you happen to know the reason for this error code, please leave a comment at https://ews.1a23.studio/issues/55 .


```

Manual linking also reports an error: 
![image](https://user-images.githubusercontent.com/94276146/167753823-53697b3c-1b7f-4b64-a3c2-be48d4f774cd.png)

![image](https://user-images.githubusercontent.com/94276146/167753837-ed6cad25-3740-482d-beb5-c8da3e0433d6.png)

![image](https://user-images.githubusercontent.com/94276146/167753848-7e80c52a-ec6f-40a2-b099-143f3d4eba03.png)

![image](https://user-images.githubusercontent.com/94276146/167753864-ca97b849-2926-4b7f-92d3-0568dff14b69.png)

![image](https://user-images.githubusercontent.com/94276146/167753878-04dfb794-8adf-4cf5-8900-f3f8ddb6173a.png)

**Comment by FlechazoPh** [comment]
The ehforwarderbot Version Info:

[root@oracle-centos-2 ~]# /usr/local/bin/ehforwarderbot -V
EH Forwarder Bot
Version: 2.1.1
Python version:
3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.2.4 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.7 # Default instance

Middlewares:
    No middleware is enabled.

**Comment by blueset** [comment]
1. For the _Link chat_ button not working, it is a known bug of Telegram iOS, there is nothing we can do to fix this.  
   The bug is tracked here: https://bugs.telegram.org/c/16647
2. When copying the _Link manually_ command, please tap the text directly to copy, or to copy it **without format**. When sent with a format, the message will not be recognized by Telegram as a bot command.

**Comment by FlechazoPh** [comment]
> 1. For the _Link chat_ button not working, it is a known bug of Telegram iOS, there is nothing we can do to fix this.
>    The bug is tracked here: https://bugs.telegram.org/c/16647
> 2. When copying the _Link manually_ command, please tap the text directly to copy, or to copy it **without format**. When sent with a format, the message will not be recognized by Telegram as a bot command.

The second way worked, and there is no bug on PC client , thanks a lot
